config/routes.rb
Rails.application.routes.draw do
  resources :articles
  root 'articles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
  end

  def create
    @article = Article.new(params.require(:article).permit(:title, :text))
    @article.save!
    redirect_to @article
  end

  def show
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<%= content_tag(:h1,'Listing articles', class: 'govuk-heading-xl') %>

<%= link_to 'New article', new_article_path, class: 'govuk-button' %>
<table class="govuk-table" >
  <thead class="govuk-table__head">
  <tr class="govuk-table__row">
    <th class="govuk-table__header">Title</th>
    <th class="govuk-table__header">Text</th>
    <th class="govuk-table__header"></th>
  </tr>
  </thead>
  <tbody class="govuk-table__body">
  <% @articles.each do |article| %>
    <tr class="govuk-table__row">
      <td class="govuk-table__cell"><%= article.title %></td>
      <td class="govuk-table__cell"><%= article.text %></td>
      <td class="govuk-table__cell"><%= link_to 'Show', article_path(article), class: 'govuk-link' %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/articles/new.html.erb
<%= form_with scope: :article, url: articles_path, local: true do |form| %>
  <p>
  <%= form.label :title %><br>
  <%= form.text_field :title %>
  </p>

  <p>
  <%= form.label :text %><br>
  <%= form.text_area :text %>
  </p>

  <p>
  <%= form.submit %>
  </p>
<% end %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
    <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
    <%= @article.text %>
</p>